---
- name: Setup system configuration
  vars_files:
    - default-config.yml
  hosts: all
  roles:
    - role: bootstrap
    - role: software
    - role: dotfiles
      when: configure_dotfiles
  environment: "{{ proxy_env | default({}) }}"
